title: Strongly Against
description: > # this means to ignore newlines until "baseurl:"
  If you could live forever, who would you want to become?
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://stronglyagainst.com" # the base hostname & protocol for your site, e.g. http://example.com

# Author Settings
author: Strongly Against # add your name
author-img: red_logo.png # add your photo
about-author:
  If you could live forever, who would you want to become?
social-twitter: freakybit_zero
social-email: freakybit.zero@gmail.com

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
